[env]
TERM = "xterm-256color"

[window]
title = "Alacritty"
decorations = "none"
dynamic_padding = false

[window.padding]
x = 5
y = 5

[scrolling]
history = 1000
multiplier = 3

[font]
size = 7

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "ExtraBold"

[font.italic]
family = "JetBrains Mono"
style = "Bold Italic"

# Gruvbox Dark (regular)
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

