theme = 'gruvbox'

# Enable soft wrap
[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""

# Keybindings
[keys.normal]
# Bind ; to reload the config
";" = ":config-reload"
